# Generated by Django 3.1.7 on 2021-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationdetail_gstno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetail',
            name='gstno',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
