# Generated by Django 3.1.6 on 2021-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='security_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
