# Generated by Django 3.1.6 on 2021-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210301_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='security_key',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
